version: '3.1'

services:
  zap:
    image: owasp/zap2docker-bare
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -addonupdate -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    user: root
    volumes:
      - ./zap/session:/root/.ZAP/session/

  glue:
    build: ./zap/glue
    working_dir: /glue/data
    command: ./test.sh
    environment:
      - ZAP_HOST=http://zap
      - ZAP_PORT=8090
    volumes:
      - ./zap/glue:/glue/data

  e2e-ui:
    depends_on:
      - zap
    environment:
      - PROXY_URL=http://zap:8090
  
  smoke-tests:
    depends_on:
      - zap
    environment:
      - PROXY_URL=http://zap:8090
