version: '2'
services:
  keys:
    image: soluto/tweek-test-keys
    build: ../deployments/dev/ssh
    
  git:
    image: soluto/tweek-bare-repo
    build: ../services/git-service/BareRepository
    ports: 
      - "5001:22"
  
  management:
    image: soluto/tweek-management
    build: ../services/management
    logging:
      driver: "json-file"
    ports:
      - "5002:3000"

  api:
    image: soluto/tweek-api
    build:
      context: ../
      dockerfile: TweekApiDockerfile
    logging:
      driver: "json-file"
    ports:
      - "5003:80"
      
  authoring:
    image: soluto/tweek-authoring
    build: ../services/authoring
    logging:
      driver: "json-file"
    ports:
      - "5005:3000"
      
  editor:
    image: soluto/tweek-editor
    build: ../services/editor
    logging:
      driver: "json-file"
    ports:
      - "5004:3000"

  zap-smoke:
    volumes:
      - ../deployments/dev/zap/session:/root/.ZAP/session/

  zap-e2e:
    volumes:
      - ../deployments/dev/zap/session:/root/.ZAP/session/

  smoke-tests:
    build:
      context: ../
      dockerfile: TweekApiSmokeTestDockerfile
    depends_on: 
      - api
      - management
      - zap-smoke
    environment: 
      - TWEEK_API_URL=http://api/
      - PROXY_URL=http://zap-smoke:8090

  e2e-ui:
    build: ../e2e/ui
    volumes_from:
      - keys
    depends_on: 
      - selenium
      - editor
      - authoring
      - api
      - management
      - zap-e2e
    environment:
      - EDITOR_URL=http://editor:3000/
      - TWEEK_API_URL=http://api/
      - AUTHORING_URL=http://authoring:3000
      - GIT_PRIVATE_KEY_PATH=/gitkeys/tweekgit
      - PROXY_URL=http://zap-e2e:8090

  e2e-integration:
    build: ../e2e/integration
    volumes_from:
      - keys
    depends_on: 
      - authoring
      - api
      - management
    environment:
      - API_URL=http://api
      - AUTHORING_URL=http://authoring:3000
      - MANAGEMENT_URL=http://tweek-management:3000
      - GIT_PRIVATE_KEY_PATH=/gitkeys/tweekgit

  zap:
    image: owasp/zap2docker-bare
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config database.recoverylog=false -config connection.timeoutInSecs=120 -addonupdate -addoninstall pscanrulesAlpha -addoninstall pscanrulesBeta -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
    user: root
    volumes:
      - ../deployments/dev/zap/session:/root/.ZAP/session/

  glue:
    build: ../deployments/dev/zap/glue
    working_dir: /glue/data
    command: ./test.sh
    depends_on: 
      - zap
    environment:
      - ZAP_HOST=http://zap
      - ZAP_PORT=8090
    volumes:
      - ../deployments/dev/zap/glue:/glue/data
